# Generated by Django 5.2.6 on 2025-09-16 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrimonio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFERIDO', 'Conferido'), ('DIVERGENTE', 'Divergente'), ('NAO_LOCALIZADO', 'NÃ£o Localizado'), ('SEM_REGISTRO', 'Sem Registro')], max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vistorias/')),
                ('foto_marcada', models.ImageField(blank=True, null=True, upload_to='vistorias/')),
                ('foto_watermarked', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='patrimonio.bem')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario')),
                ('sala_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.sala')),
                ('vistoriador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
