# Generated by Django 5.2.6 on 2025-09-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('novos', models.PositiveIntegerField(default=0)),
                ('atualizados', models.PositiveIntegerField(default=0)),
                ('movidos', models.PositiveIntegerField(default=0)),
                ('baixados', models.PositiveIntegerField(default=0)),
                ('reativados', models.PositiveIntegerField(default=0)),
                ('sem_mudanca', models.PositiveIntegerField(default=0)),
                ('ausentes', models.PositiveIntegerField(default=0)),
                ('aplicado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(max_length=50)),
                ('acao', models.CharField(choices=[('NOVO', 'Novo'), ('ATUALIZADO', 'Atualizado'), ('MOVIDO', 'Movido'), ('BAIXADO', 'Baixado'), ('REATIVADO', 'Reativado'), ('SEM_MUDANCA', 'Sem Mudança'), ('AUSENTE', 'Ausente')], max_length=20)),
                ('mudancas', models.JSONField(blank=True, default=dict)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventarios.importacao')),
            ],
        ),
    ]
