# Generated by Django 5.2.6 on 2025-09-16 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_importacao_importacaoitem'),
        ('patrimonio', '0006_bem_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento_informado', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sem_registro/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sem_registro', to='inventarios.inventario')),
                ('sala_encontrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonio.sala')),
                ('vistoriador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
