# Generated by Django 5.2.6 on 2025-09-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_semregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-ativo', '-ano']},
        ),
        migrations.AlterModelOptions(
            name='vistoria',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveField(
            model_name='importacaoitem',
            name='mudancas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='foto_marcada',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='foto_watermarked',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vistoria',
            name='longitude',
        ),
        migrations.AddField(
            model_name='importacaoitem',
            name='diff',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='estado_encontrado',
            field=models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='responsavel_encontrado',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='inventarios.inventario'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='observacao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='vistoriador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
