# Generated by Django 5.2.6 on 2025-09-18 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_alter_importacao_options_alter_inventario_options_and_more'),
        ('patrimonio', '0006_bem_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vistoria',
            constraint=models.UniqueConstraint(fields=('inventario', 'bem'), name='uniq_vistoria_por_bem_no_inventario'),
        ),
    ]
