# Generated by Django 5.2.6 on 2025-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_vistoria_uniq_vistoria_por_bem_no_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoitem',
            name='mudancas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importacaoitem',
            name='acao',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('ATUALIZADO', 'Atualizado'), ('MOVIDO', 'Movido'), ('BAIXADO', 'Baixado'), ('REATIVADO', 'Reativado'), ('SEM_MUDANCA', 'Sem MudanÃ§a'), ('AUSENTE', 'Ausente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='estado_encontrado',
            field=models.CharField(blank=True, choices=[('OTIMO', 'Ã“timo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'InservÃ\xadvel')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='status',
            field=models.CharField(choices=[('CONFERIDO', 'Conferido'), ('DIVERGENTE', 'Divergente'), ('NAO_LOCALIZADO', 'NÃ£o Localizado'), ('SEM_REGISTRO', 'Sem Registro')], max_length=20),
        ),
    ]
