# Generated by Django 5.2.6 on 2025-09-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('bloco', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombamento', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, default='', max_length=120)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('sala_oficial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_oficiais', to='patrimonio.sala')),
            ],
            options={
                'verbose_name_plural': 'Bens',
            },
        ),
    ]
