# Generated by Django 5.2.6 on 2025-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='info_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
