# Generated by Django 5.2.6 on 2025-09-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_bem_info_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='campus_carga',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='carga_atual',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='carga_contabil',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='conta_contabil',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bem',
            name='data_carga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='ed',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bem',
            name='estado_conservacao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='fornecedor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bem',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bem',
            name='rotulos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bem',
            name='sala_texto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='setor_responsavel',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bem',
            name='status_original',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='bem',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='valor_depreciado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
