# Generated by Django 5.2.6 on 2025-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_bem_campus_carga_bem_carga_atual_bem_carga_contabil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('nome', 'bloco'), name='unique_sala_nome_bloco'),
        ),
    ]
