# Generated by Django 5.2.6 on 2025-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_alter_sala_nome_sala_unique_sala_nome_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='modelo',
        ),
        migrations.AddField(
            model_name='bem',
            name='ausente_no_ultimo_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bem',
            name='baixado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='ultima_atualizacao_csv',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
