# Generated by Django 5.2.6 on 2025-09-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_remove_bem_marca_remove_bem_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='tipo',
            field=models.CharField(choices=[('BEM', 'Bem'), ('LIVRO', 'Livro')], default='BEM', max_length=10),
        ),
    ]
