# Generated by Django 5.2.6 on 2025-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_bem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='descricao',
            field=models.CharField(max_length=1024),
        ),
    ]
